// Generated by StonicAi_main/scripts/build-agent-town.js — do not edit.
const fs = require('fs');
const path = require('path');

// next/dist/server/config.js short-circuits to this value when set, which is how
// a standalone build boots without a next.config on disk.
const requiredServerFiles = path.join(__dirname, '.next', 'required-server-files.json');
if (fs.existsSync(requiredServerFiles)) {
  process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(
    JSON.parse(fs.readFileSync(requiredServerFiles, 'utf8')).config
  );
}

// The custom server calls next({ dev: false }), which resolves the app from cwd.
process.chdir(__dirname);
process.env.NODE_ENV = 'production';

require('./server-bundle.cjs');
